apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-oowf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-oowf
    app.kubernetes.io/part-of: node-gateway
  name: devfile-sample-oowf
  namespace: phayes1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-oowf
status:
  loadBalancer: {}
