apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-h4vy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-h4vy
    app.kubernetes.io/part-of: node-gateway
  name: demojam-gateway-h4vy
  namespace: phayes1-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: demojam-gateway-h4vy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: demojam-gateway-h4vy
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:42918f5523da578cb33c0c8c3c2539d0f14754b5fbfadfc8467a4d06299eaed2
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
