apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: demojam-gateway-h4vy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: demojam-gateway-h4vy
    app.kubernetes.io/part-of: node-gateway
  name: demojam-gateway-h4vy
  namespace: phayes1-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: demojam-gateway-h4vy
status:
  loadBalancer: {}
